import SwiftUI

/// The shared printable A4 page chrome for every Statistics PDF export: title, report name,
/// data/chart-type/range subtitle, generation timestamp, hardware/software/settings metadata,
/// and footer. Callers supply the chart-specific body as `content`, forced to light,
/// print-friendly styling so the export looks the same regardless of the device's color scheme.
struct StatPDFPage<Content: View>: View {
    let reportName: String
    let dataTypeDisplayName: String
    let chartTypeDisplayName: String
    let rangeDisplayName: String
    let periodStart: Date
    let periodEnd: Date
    let generatedAt: Date
    let reportMetadata: Stat.StateModel.ReportMetadata
    let content: Content

    init(
        reportName: String,
        dataTypeDisplayName: String,
        chartTypeDisplayName: String,
        rangeDisplayName: String,
        periodStart: Date,
        periodEnd: Date,
        generatedAt: Date,
        reportMetadata: Stat.StateModel.ReportMetadata,
        @ViewBuilder content: () -> Content
    ) {
        self.reportName = reportName
        self.dataTypeDisplayName = dataTypeDisplayName
        self.chartTypeDisplayName = chartTypeDisplayName
        self.rangeDisplayName = rangeDisplayName
        self.periodStart = periodStart
        self.periodEnd = periodEnd
        self.generatedAt = generatedAt
        self.reportMetadata = reportMetadata
        self.content = content()
    }

    private let margin: CGFloat = 32

    var body: some View {
        VStack(alignment: .leading, spacing: 20) {
            header

            Divider()

            content

            Spacer(minLength: 0)

            footer
        }
        .padding(margin)
        .frame(width: StatPDFExporter.pageSize.width, height: StatPDFExporter.pageSize.height, alignment: .topLeading)
        .background(Color.white)
        .foregroundStyle(Color.black)
    }

    private var header: some View {
        VStack(alignment: .leading, spacing: 4) {
            Text("Trio — Statistics Report")
                .font(.title2)
                .fontWeight(.bold)

            if !reportName.isEmpty {
                Text(reportName)
                    .font(.headline)
            }

            Text("\(dataTypeDisplayName) · \(chartTypeDisplayName) · \(rangeDisplayName) (\(dateRangeText))")
                .font(.subheadline)
                .foregroundStyle(Color.secondary)

            Text("Generated \(generatedAt.formatted(date: .abbreviated, time: .shortened))")
                .font(.caption)
                .foregroundStyle(Color.secondary)

            metaInfo
                .padding(.top, 4)
        }
    }

    private var metaInfo: some View {
        VStack(alignment: .leading, spacing: 6) {
            VStack(alignment: .leading, spacing: 1) {
                Text("Hardware in use").fontWeight(.semibold).foregroundStyle(Color.black)
                Text(
                    "CGM: \(reportMetadata.hardware.cgmName) · Pump: \(reportMetadata.hardware.pumpName) · iPhone: \(reportMetadata.hardware.iPhoneType)"
                )
                .foregroundStyle(Color.secondary)
            }

            VStack(alignment: .leading, spacing: 1) {
                Text("Software in use").fontWeight(.semibold).foregroundStyle(Color.black)
                Text("Trio \(reportMetadata.software.trioVersion) · Build \(reportMetadata.software.buildDate)")
                    .foregroundStyle(Color.secondary)
            }

            VStack(alignment: .leading, spacing: 1) {
                Text("Important settings").fontWeight(.semibold).foregroundStyle(Color.black)
                Text(
                    "Dynamic ISF: \(onOffText(reportMetadata.importantSettings.dynamicISFEnabled)) · SMB: \(onOffText(reportMetadata.importantSettings.smbEnabled)) · UAM: \(onOffText(reportMetadata.importantSettings.uamEnabled)) · Closed Loop: \(onOffText(reportMetadata.importantSettings.closedLoopActive))"
                )
                .foregroundStyle(Color.secondary)
            }
        }
        .font(.caption2)
    }

    private func onOffText(_ enabled: Bool) -> String {
        enabled ? String(localized: "On") : String(localized: "Off")
    }

    private var footer: some View {
        Text("Generated by Trio")
            .font(.caption2)
            .foregroundStyle(Color.secondary)
            .frame(maxWidth: .infinity, alignment: .center)
    }

    private var dateRangeText: String {
        "\(periodStart.formatted(date: .abbreviated, time: .omitted)) – \(periodEnd.formatted(date: .abbreviated, time: .omitted))"
    }
}
